version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: djk8s-compose:v1
    environment:
      - PORT=8023
    env_file:
      - .env
    ports:
      - "8001:8023"
